import { Box, Container, useColorModeValue, VStack } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../components/layouts/applayout';
import ThemeButton from '../components/ThemeButton';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <Box className={styles.container}>
      <Head>
        <title>My Chat App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <ThemeButton />
      </Layout>
    </Box>
  );
};

export default Home;
