import {
  Box,
  Container,
  Flex,
  Text,
  useColorModeValue,
  VStack,
} from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import ContactCard from '../components/ContactCard';
import Layout from '../components/layouts/applayout';
import ThemeButton from '../components/ThemeButton';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <Box className={styles.container}>
      <Head>
        <title>My Chat App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Flex gap={'1rem'}>
          <VStack h={'100%'} width={'fit-content'}>
            <ThemeButton />
          </VStack>
          <VStack width={'25%'} py={'1rem'}>
            <ContactCard name='Juan' />
            <ContactCard name='Melissa' />
            <ContactCard name='Andres' />
          </VStack>
          <Box>Hello</Box>
        </Flex>
      </Layout>
    </Box>
  );
};

export default Home;
